#!/usr/bin/env bash

echo RANCHER_COM_GPU_MEM_DEV=$RANCHER_COM_GPU_MEM_DEV
echo RANCHER_COM_GPU_MEM_CONTAINER=$RANCHER_COM_GPU_MEM_CONTAINER

python /classification.py --total=$RANCHER_COM_GPU_MEM_DEV --allocated=$RANCHER_COM_GPU_MEM_CONTAINER
